services:
  db:
    image: mysql:8
    container_name: meetingroom-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meetingroom
      TZ: Asia/Seoul
    ports:
      - "3305:3306"
    volumes:
      - db:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meetingroom-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      TZ: "Asia/Seoul"
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/meetingroom?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
volumes:
  db: